# Generated by Django 5.2.12 on 2026-04-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="sale",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="sale",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "Paid in Full"), ("partial", "Part Payment")],
                default="paid",
                max_length=20,
            ),
        ),
    ]
