# Generated by Django 5.2.12 on 2026-04-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_options_alter_product_options_and_more"),
        ("sales", "0002_sale_amount_paid_sale_balance_sale_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="sales",
                through="sales.SaleItem",
                to="products.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.UniqueConstraint(
                fields=("sale", "product"), name="unique_product_per_sale"
            ),
        ),
    ]
