# Generated by Django 5.2.12 on 2026-04-20 13:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_company_referred_by_affiliate"),
        ("products", "0003_supplier_productsupply_and_more"),
        ("sales", "0003_sale_products_saleitem_unique_product_per_sale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("payment_status", models.CharField(default="pending", max_length=20)),
                ("due_status", models.CharField(default="due", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid in Full"),
                    ("partial", "Part Payment"),
                    ("zero", "Zero Payment"),
                ],
                default="paid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("unpaid", "Unpaid"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["company", "created_at"], name="sales_sale_company_28d719_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["company", "status"], name="sales_sale_company_2c1921_idx"
            ),
        ),
        migrations.AddField(
            model_name="paymentreceipt",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_receipts",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="paymentreceipt",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentreceipt",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="sales.sale",
            ),
        ),
        migrations.AddField(
            model_name="saleinvoice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_invoices",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="saleinvoice",
            name="sale",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="sales.sale",
            ),
        ),
        migrations.AddField(
            model_name="paymentreceipt",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="sales.saleinvoice",
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_payments",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_sale_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salepayment",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="sales.sale",
            ),
        ),
        migrations.AddField(
            model_name="paymentreceipt",
            name="sale_payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt",
                to="sales.salepayment",
            ),
        ),
        migrations.AddIndex(
            model_name="salepayment",
            index=models.Index(
                fields=["company", "created_at"], name="sales_salep_company_52a4f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salepayment",
            index=models.Index(
                fields=["sale", "created_at"], name="sales_salep_sale_id_a281e6_idx"
            ),
        ),
    ]
