# Generated by Django 5.2.12 on 2026-04-15 10:03

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="companies_company_name_ci_unique",
            ),
        ),
    ]
