# Generated by Django 5.2.12 on 2026-04-19 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_companies_company_name_ci_unique"),
        ("users", "0004_affiliate"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="referred_by_affiliate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_companies",
                to="users.affiliate",
            ),
        ),
    ]
