# Generated by Django 6.0.3 on 2026-04-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('user', 'User')], default='staff', max_length=20),
        ),
    ]
