# Generated by Django 5.2.12 on 2026-04-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_affiliate"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_affiliate",
            field=models.BooleanField(default=False),
        ),
    ]
